#pragma once

#define gpfbase	0x11400000
#define GPD0CON	(*(volatile unsigned long *)(gpfbase + 0xa0))
#define GPD0DAT (*(volatile unsigned long *)(gpfbase + 0xa4))
#define GPD0PUD (*(volatile unsigned long *)(gpfbase + 0xa8))

#define GPF0CON		(*(volatile unsigned long *)(gpfbase + 0x0180))
#define GPF1CON 	(*(volatile unsigned long *)(gpfbase + 0x01a0))
#define GPF2CON		(*(volatile unsigned long *)(gpfbase + 0x01c0))
#define GPF3CON		(*(volatile unsigned long *)(gpfbase + 0x01E0))

#define gpmbase	0x11000000
#define GPM4CON 	(*(volatile unsigned long *)(gpmbase + 0x02e0)) 
#define GPM4DAT		(*(volatile unsigned long *)(gpmbase + 0x02e4))

#define GPX3CON		(*(volatile unsigned long *)(gpmbase + 0x0C60))
#define GPX3DAT		(*(volatile unsigned long *)(gpmbase + 0x0C64))
#define GPX3PUD		(*(volatile unsigned long *)(gpmbase + 0x0C68))

#define	EXT_INT43CON 	(*(volatile unsigned long *)(gpmbase + 0x0e0c))
#define	EXT_INT43_MASK  (*(volatile unsigned long *)(gpmbase + 0x0f0c))
#define	EXT_INT43_PEND  (*(volatile unsigned long *)(gpmbase + 0x0f4c))

#define gicbase		0x10480000
#define ICCICR_CPU0	(*(volatile unsigned long *)(gicbase + 0x0))
#define ICCPMR_CPU0	(*(volatile unsigned long *)(gicbase + 0x4))
#define ICCBPR_CPU0	(*(volatile unsigned long *)(gicbase + 0x8))
#define ICCIAR_CPU0     (*(volatile unsigned long *)(gicbase + 0xc))
#define ICCEOIR_CPU0    (*(volatile unsigned long *)(gicbase + 0x10))
#define ICCRPR_CPU0 	(*(volatile unsigned long *)(gicbase + 0x14))
#define ICCHPIR_CPU0	(*(volatile unsigned long *)(gicbase + 0x18))
#define ICCABPR_CPU0	(*(volatile unsigned long *)(gicbase + 0x1c))
#define INTEG_EN_C_CPU0 (*(volatile unsigned long *)(gicbase + 0x40))
#define INTERRUPT_OUT_CPU0  (*(volatile unsigned long *)(gicbase + 0x44))

#define ICCIIDR   (*(volatile unsigned long *)(gicbase + 0xfc))

#define icdbase	0x10490000
#define ICDDCR    (*(volatile unsigned long *)(icdbase + 0x0))
#define ICDICTR   (*(volatile unsigned long *)(icdbase + 0x4))
#define ICDIIDR   (*(volatile unsigned long *)(icdbase + 0x8))

#define ICDISR0_CPU0 (*(volatile unsigned long *)(icdbase + 0x0080))
#define ICDISR1_CPU0 (*(volatile unsigned long *)(icdbase + 0x0084))
#define ICDISR2_CPU0 (*(volatile unsigned long *)(icdbase + 0x0088))
#define ICDISR3_CPU0 (*(volatile unsigned long *)(icdbase + 0x008C))
#define ICDISR4_CPU0 (*(volatile unsigned long *)(icdbase + 0x0090))

#define ICDISER0_CPU0 (*(volatile unsigned long *)(icdbase + 0x0100))
#define ICDISER1_CPU0 (*(volatile unsigned long *)(icdbase + 0x0104))
#define ICDISER2_CPU0 (*(volatile unsigned long *)(icdbase + 0x0108))
#define ICDISER3_CPU0 (*(volatile unsigned long *)(icdbase + 0x010C))
#define ICDISER4_CPU0 (*(volatile unsigned long *)(icdbase + 0x0110))

#define ICDICER0_CPU0 (*(volatile unsigned long *)(icdbase + 0x0180))
#define ICDICER1_CPU0 (*(volatile unsigned long *)(icdbase + 0x0184))
#define ICDICER2_CPU0 (*(volatile unsigned long *)(icdbase + 0x0188))
#define ICDICER3_CPU0 (*(volatile unsigned long *)(icdbase + 0x018C))
#define ICDICER4_CPU0 (*(volatile unsigned long *)(icdbase + 0x0190))

#define ICDISPR0_CPU0 (*(volatile unsigned long *)(icdbase + 0x0200))
#define ICDISPR1_CPU0 (*(volatile unsigned long *)(icdbase + 0x0204))
#define ICDISPR2_CPU0 (*(volatile unsigned long *)(icdbase + 0x0208))
#define ICDISPR3_CPU0 (*(volatile unsigned long *)(icdbase + 0x020C))
#define ICDISPR4_CPU0 (*(volatile unsigned long *)(icdbase + 0x0210))

#define ICDICPR0_CPU0 (*(volatile unsigned long *)(icdbase + 0x0280))
#define ICDICPR1_CPU0 (*(volatile unsigned long *)(icdbase + 0x0284))
#define ICDICPR2_CPU0 (*(volatile unsigned long *)(icdbase + 0x0288))
#define ICDICPR3_CPU0 (*(volatile unsigned long *)(icdbase + 0x028C))
#define ICDICPR4_CPU0 (*(volatile unsigned long *)(icdbase + 0x0290))

#define ICDABR0_CPU0  (*(volatile unsigned long *)(icdbase + 0x0300))
#define ICDABR1_CPU0  (*(volatile unsigned long *)(icdbase + 0x0304))
#define ICDABR2_CPU0  (*(volatile unsigned long *)(icdbase + 0x0308))
#define ICDABR3_CPU0  (*(volatile unsigned long *)(icdbase + 0x030C))
#define ICDABR4_CPU0  (*(volatile unsigned long *)(icdbase + 0x0310))

#define ICDIPR0_CPU0  (*(volatile unsigned long *)(icdbase + 0x0400)) 
#define ICDIPR1_CPU0  (*(volatile unsigned long *)(icdbase + 0x0404)) 
#define ICDIPR2_CPU0  (*(volatile unsigned long *)(icdbase + 0x0408)) 
#define ICDIPR3_CPU0  (*(volatile unsigned long *)(icdbase + 0x040C)) 
#define ICDIPR4_CPU0  (*(volatile unsigned long *)(icdbase + 0x0410)) 
#define ICDIPR5_CPU0  (*(volatile unsigned long *)(icdbase + 0x0414)) 
#define ICDIPR6_CPU0  (*(volatile unsigned long *)(icdbase + 0x0418)) 
#define ICDIPR7_CPU0  (*(volatile unsigned long *)(icdbase + 0x041C)) 
#define ICDIPR8_CPU0  (*(volatile unsigned long *)(icdbase + 0x0420)) 
#define ICDIPR9_CPU0  (*(volatile unsigned long *)(icdbase + 0x0424)) 
#define ICDIPR10_CPU0 (*(volatile unsigned long *)(icdbase + 0x0428))
#define ICDIPR11_CPU0 (*(volatile unsigned long *)(icdbase + 0x042C))
#define ICDIPR12_CPU0 (*(volatile unsigned long *)(icdbase + 0x0430))
#define ICDIPR13_CPU0 (*(volatile unsigned long *)(icdbase + 0x0434))
#define ICDIPR14_CPU0 (*(volatile unsigned long *)(icdbase + 0x0438))
#define ICDIPR15_CPU0 (*(volatile unsigned long *)(icdbase + 0x043C))
#define ICDIPR16_CPU0 (*(volatile unsigned long *)(icdbase + 0x0440))
#define ICDIPR17_CPU0 (*(volatile unsigned long *)(icdbase + 0x0444))
#define ICDIPR18_CPU0 (*(volatile unsigned long *)(icdbase + 0x0448))
#define ICDIPR19_CPU0 (*(volatile unsigned long *)(icdbase + 0x044C))
#define ICDIPR20_CPU0 (*(volatile unsigned long *)(icdbase + 0x0450))
#define ICDIPR21_CPU0 (*(volatile unsigned long *)(icdbase + 0x0454))
#define ICDIPR22_CPU0 (*(volatile unsigned long *)(icdbase + 0x0458))
#define ICDIPR23_CPU0 (*(volatile unsigned long *)(icdbase + 0x045C))
#define ICDIPR24_CPU0 (*(volatile unsigned long *)(icdbase + 0x0460))
#define ICDIPR25_CPU0 (*(volatile unsigned long *)(icdbase + 0x0464))
#define ICDIPR26_CPU0 (*(volatile unsigned long *)(icdbase + 0x0468))
#define ICDIPR27_CPU0 (*(volatile unsigned long *)(icdbase + 0x046C))
#define ICDIPR28_CPU0 (*(volatile unsigned long *)(icdbase + 0x0470))
#define ICDIPR29_CPU0 (*(volatile unsigned long *)(icdbase + 0x0474))
#define ICDIPR30_CPU0 (*(volatile unsigned long *)(icdbase + 0x0478))
#define ICDIPR31_CPU0 (*(volatile unsigned long *)(icdbase + 0x047C))
#define ICDIPR32_CPU0 (*(volatile unsigned long *)(icdbase + 0x0480))
#define ICDIPR33_CPU0 (*(volatile unsigned long *)(icdbase + 0x0484))
#define ICDIPR34_CPU0 (*(volatile unsigned long *)(icdbase + 0x0488))
#define ICDIPR35_CPU0 (*(volatile unsigned long *)(icdbase + 0x048C))
#define ICDIPR36_CPU0 (*(volatile unsigned long *)(icdbase + 0x0490))
#define ICDIPR37_CPU0 (*(volatile unsigned long *)(icdbase + 0x0494))
#define ICDIPR38_CPU0 (*(volatile unsigned long *)(icdbase + 0x0498))
#define ICDIPR39_CPU0 (*(volatile unsigned long *)(icdbase + 0x049C))

#define ICDIPTR0_CPU0  (*(volatile unsigned long *)(icdbase + 0x0800))
#define ICDIPTR1_CPU0  (*(volatile unsigned long *)(icdbase + 0x0804))
#define ICDIPTR2_CPU0  (*(volatile unsigned long *)(icdbase + 0x0808))
#define ICDIPTR3_CPU0  (*(volatile unsigned long *)(icdbase + 0x080C))
#define ICDIPTR4_CPU0  (*(volatile unsigned long *)(icdbase + 0x0810))
#define ICDIPTR5_CPU0  (*(volatile unsigned long *)(icdbase + 0x0814))
#define ICDIPTR6_CPU0  (*(volatile unsigned long *)(icdbase + 0x0818))
#define ICDIPTR7_CPU0  (*(volatile unsigned long *)(icdbase + 0x081C))
#define ICDIPTR8_CPU0  (*(volatile unsigned long *)(icdbase + 0x0820))
#define ICDIPTR9_CPU0  (*(volatile unsigned long *)(icdbase + 0x0824))
#define ICDIPTR10_CPU0 (*(volatile unsigned long *)(icdbase + 0x0828))
#define ICDIPTR11_CPU0 (*(volatile unsigned long *)(icdbase + 0x082C))
#define ICDIPTR12_CPU0 (*(volatile unsigned long *)(icdbase + 0x0830))
#define ICDIPTR13_CPU0 (*(volatile unsigned long *)(icdbase + 0x0834))
#define ICDIPTR14_CPU0 (*(volatile unsigned long *)(icdbase + 0x0838))
#define ICDIPTR15_CPU0 (*(volatile unsigned long *)(icdbase + 0x083C))
#define ICDIPTR16_CPU0 (*(volatile unsigned long *)(icdbase + 0x0840))
#define ICDIPTR17_CPU0 (*(volatile unsigned long *)(icdbase + 0x0844))
#define ICDIPTR18_CPU0 (*(volatile unsigned long *)(icdbase + 0x0848))
#define ICDIPTR19_CPU0 (*(volatile unsigned long *)(icdbase + 0x084C))
#define ICDIPTR20_CPU0 (*(volatile unsigned long *)(icdbase + 0x0850))
#define ICDIPTR21_CPU0 (*(volatile unsigned long *)(icdbase + 0x0854))
#define ICDIPTR22_CPU0 (*(volatile unsigned long *)(icdbase + 0x0858))
#define ICDIPTR23_CPU0 (*(volatile unsigned long *)(icdbase + 0x085C))
#define ICDIPTR24_CPU0 (*(volatile unsigned long *)(icdbase + 0x0860))
#define ICDIPTR25_CPU0 (*(volatile unsigned long *)(icdbase + 0x0864))
#define ICDIPTR26_CPU0 (*(volatile unsigned long *)(icdbase + 0x0868))
#define ICDIPTR27_CPU0 (*(volatile unsigned long *)(icdbase + 0x086C))
#define ICDIPTR28_CPU0 (*(volatile unsigned long *)(icdbase + 0x0870))
#define ICDIPTR29_CPU0 (*(volatile unsigned long *)(icdbase + 0x0874))
#define ICDIPTR30_CPU0 (*(volatile unsigned long *)(icdbase + 0x0878))
#define ICDIPTR31_CPU0 (*(volatile unsigned long *)(icdbase + 0x087C))
#define ICDIPTR32_CPU0 (*(volatile unsigned long *)(icdbase + 0x0880))
#define ICDIPTR33_CPU0 (*(volatile unsigned long *)(icdbase + 0x0884))
#define ICDIPTR34_CPU0 (*(volatile unsigned long *)(icdbase + 0x0888))
#define ICDIPTR35_CPU0 (*(volatile unsigned long *)(icdbase + 0x088C))
#define ICDIPTR36_CPU0 (*(volatile unsigned long *)(icdbase + 0x0890))
#define ICDIPTR37_CPU0 (*(volatile unsigned long *)(icdbase + 0x0894))
#define ICDIPTR38_CPU0 (*(volatile unsigned long *)(icdbase + 0x0898))
#define ICDIPTR39_CPU0 (*(volatile unsigned long *)(icdbase + 0x089C))


#define ICDICFR0_CPU0 (*(volatile unsigned long *)(icdbase + 0x0C00))
#define ICDICFR1_CPU0 (*(volatile unsigned long *)(icdbase + 0x0C04))
#define ICDICFR2_CPU0 (*(volatile unsigned long *)(icdbase + 0x0C08))
#define ICDICFR3_CPU0 (*(volatile unsigned long *)(icdbase + 0x0C0C))
#define ICDICFR4_CPU0 (*(volatile unsigned long *)(icdbase + 0x0C10))
#define ICDICFR5_CPU0 (*(volatile unsigned long *)(icdbase + 0x0C14))
#define ICDICFR6_CPU0 (*(volatile unsigned long *)(icdbase + 0x0C18))
#define ICDICFR7_CPU0 (*(volatile unsigned long *)(icdbase + 0x0C1C))
#define ICDICFR8_CPU0 (*(volatile unsigned long *)(icdbase + 0x0C20))
#define ICDICFR9_CPU0 (*(volatile unsigned long *)(icdbase + 0x0C24))

#define PPI_STATUS_CPU0 (*(volatile unsigned long *)(icdbase + 0x0D00))

#define SPI_STATUS0 (*(volatile unsigned long *)(icdbase + 0x0D04))
#define SPI_STATUS1 (*(volatile unsigned long *)(icdbase + 0x0D08))
#define SPI_STATUS2 (*(volatile unsigned long *)(icdbase + 0x0D0C))
#define SPI_STATUS3 (*(volatile unsigned long *)(icdbase + 0x0D10))

#define ICDSGIR  (*(volatile unsigned long *)(icdbase + 0x0f00))

#define wdtbase 0x10060000
#define WTCON    (*(volatile unsigned long *)(wdtbase + 0x0000)) 
#define WTDAT    (*(volatile unsigned long *)(wdtbase + 0x0004)) 
#define WTCNT    (*(volatile unsigned long *)(wdtbase + 0x0008)) 
#define WTCLRINT (*(volatile unsigned long *)(wdtbase + 0x000C)) 

#define pwmbase 0x139D0000
#define TCFG0       (*(volatile unsigned long *)(pwmbase + 0x0000)) 
#define TCFG1       (*(volatile unsigned long *)(pwmbase + 0x0004)) 
#define TCON        (*(volatile unsigned long *)(pwmbase + 0x0008)) 
#define TCNTB0      (*(volatile unsigned long *)(pwmbase + 0x000C)) 
#define TCMPB0      (*(volatile unsigned long *)(pwmbase + 0x0010)) 
#define TCNTO0      (*(volatile unsigned long *)(pwmbase + 0x0014)) 
#define TCNTB1      (*(volatile unsigned long *)(pwmbase + 0x0018)) 
#define TCMPB1      (*(volatile unsigned long *)(pwmbase + 0x001C)) 
#define TCNTO1      (*(volatile unsigned long *)(pwmbase + 0x0020)) 
#define TCNTB2      (*(volatile unsigned long *)(pwmbase + 0x0024)) 
#define TCMPB2      (*(volatile unsigned long *)(pwmbase + 0x0028)) 
#define TCNTO2      (*(volatile unsigned long *)(pwmbase + 0x002C)) 
#define TCNTB3      (*(volatile unsigned long *)(pwmbase + 0x0030)) 
#define TCMPB3      (*(volatile unsigned long *)(pwmbase + 0x0034)) 
#define TCNTO3      (*(volatile unsigned long *)(pwmbase + 0x0038)) 
#define TCNTB4      (*(volatile unsigned long *)(pwmbase + 0x003C)) 
#define TCNTO4      (*(volatile unsigned long *)(pwmbase + 0x0040)) 
#define TINT_CSTAT  (*(volatile unsigned long *)(pwmbase + 0x0044)) 

#define uart0base  0x13800000
#define ULCON0    (*(volatile unsigned long *)(uart0base + 0x0000)) 
#define UCON0     (*(volatile unsigned long *)(uart0base + 0x0004)) 
#define UFCON0    (*(volatile unsigned long *)(uart0base + 0x0008)) 
#define UMCON0    (*(volatile unsigned long *)(uart0base + 0x000C)) 
#define UTRSTAT0  (*(volatile unsigned long *)(uart0base + 0x0010)) 
#define UERSTAT0  (*(volatile unsigned long *)(uart0base + 0x0014)) 
#define UFSTAT0   (*(volatile unsigned long *)(uart0base + 0x0018)) 
#define UMSTAT0   (*(volatile unsigned long *)(uart0base + 0x001C)) 
#define UTXH0     (*(volatile unsigned char *)(uart0base + 0x0020)) 
#define URXH0     (*(volatile unsigned char *)(uart0base + 0x0024)) 
#define UBRDIV0   (*(volatile unsigned long *)(uart0base + 0x0028)) 
#define UFRACVAL0 (*(volatile unsigned long *)(uart0base + 0x002C)) 
#define UINTP0    (*(volatile unsigned long *)(uart0base + 0x0030)) 
#define UINTSP0   (*(volatile unsigned long *)(uart0base + 0x0034)) 
#define UINTM0    (*(volatile unsigned long *)(uart0base + 0x0038)) 

#define uart3base  0x13830000
#define ULCON3    (*(volatile unsigned long *)(uart3base + 0x0000)) 
#define UCON3     (*(volatile unsigned long *)(uart3base + 0x0004)) 
#define UFCON3    (*(volatile unsigned long *)(uart3base + 0x0008)) 
#define UMCON3    (*(volatile unsigned long *)(uart3base + 0x000C)) 
#define UTRSTAT3  (*(volatile unsigned long *)(uart3base + 0x0010)) 
#define UERSTAT3  (*(volatile unsigned long *)(uart3base + 0x0014)) 
#define UFSTAT3   (*(volatile unsigned long *)(uart3base + 0x0018)) 
#define UMSTAT3   (*(volatile unsigned long *)(uart3base + 0x001C)) 
#define UTXH3     (*(volatile unsigned char *)(uart3base + 0x0020)) 
#define URXH3     (*(volatile unsigned char *)(uart3base + 0x0024)) 
#define UBRDIV3   (*(volatile unsigned long *)(uart3base + 0x0028)) 
#define UFRACVAL3 (*(volatile unsigned long *)(uart3base + 0x002C)) 
#define UINTP3    (*(volatile unsigned long *)(uart3base + 0x0030)) 
#define UINTSP3   (*(volatile unsigned long *)(uart3base + 0x0034)) 
#define UINTM3    (*(volatile unsigned long *)(uart3base + 0x0038)) 

#define clkbase1 0x10030000
#define CLK_SRC_LEFTBUS              (*(volatile unsigned long *)(clkbase1 + 0x4200 ))
#define CLK_MUX_STAT_LEFTBUS         (*(volatile unsigned long *)(clkbase1 + 0x4400 ))
#define CLK_DIV_LEFTBUS              (*(volatile unsigned long *)(clkbase1 + 0x4500 ))
#define CLK_DIV_STAT_LEFTBUS         (*(volatile unsigned long *)(clkbase1 + 0x4600 ))
#define CLK_GATE_IP_LEFTBUS          (*(volatile unsigned long *)(clkbase1 + 0x4800 ))
#define CLK_GATE_IP_IMAGE            (*(volatile unsigned long *)(clkbase1 + 0x4930 ))
#define CLKOUT_CMU_LEFTBUS           (*(volatile unsigned long *)(clkbase1 + 0x4A00 ))
#define CLKOUT_CMU_LEFTBUS_DIV_STAT  (*(volatile unsigned long *)(clkbase1 + 0x4A04 ))
#define CLK_SRC_RIGHTBUS             (*(volatile unsigned long *)(clkbase1 + 0x8200 ))
#define CLK_MUX_STAT_RIGHTBUS        (*(volatile unsigned long *)(clkbase1 + 0x8400 ))
#define CLK_DIV_RIGHTBUS             (*(volatile unsigned long *)(clkbase1 + 0x8500 ))
#define CLK_DIV_STAT_RIGHTBUS        (*(volatile unsigned long *)(clkbase1 + 0x8600 ))
#define CLK_GATE_IP_RIGHTBUS         (*(volatile unsigned long *)(clkbase1 + 0x8800 ))
#define CLK_GATE_IP_PERIR            (*(volatile unsigned long *)(clkbase1 + 0x8960 ))
#define CLKOUT_CMU_RIGHTBUS 	     (*(volatile unsigned long *)(clkbase1 + 0x8A00 ))
#define CLKOUT_CMU_RIGHTBUS_DIV_STAT (*(volatile unsigned long *)(clkbase1 + 0x8A04 ))
#define EPLL_LOCK                    (*(volatile unsigned long *)(clkbase1 + 0xC010 ))
#define VPLL_LOCK                    (*(volatile unsigned long *)(clkbase1 + 0xC020 ))
#define EPLL_CON0 		     (*(volatile unsigned long *)(clkbase1 + 0xC110 ))
#define EPLL_CON1 		     (*(volatile unsigned long *)(clkbase1 + 0xC114 ))
#define EPLL_CON2 		     (*(volatile unsigned long *)(clkbase1 + 0xC118 ))
#define VPLL_CON0 		     (*(volatile unsigned long *)(clkbase1 + 0xC120 ))
#define VPLL_CON1 		     (*(volatile unsigned long *)(clkbase1 + 0xC124 ))
#define VPLL_CON2 		     (*(volatile unsigned long *)(clkbase1 + 0xC128 ))
#define CLK_SRC_TOP0 		     (*(volatile unsigned long *)(clkbase1 + 0xC210 ))
#define CLK_SRC_TOP1 		     (*(volatile unsigned long *)(clkbase1 + 0xC214 ))
#define CLK_SRC_CAM0                 (*(volatile unsigned long *)(clkbase1 + 0xC220 ))
#define CLK_SRC_TV                   (*(volatile unsigned long *)(clkbase1 + 0xC224 ))
#define CLK_SRC_MFC                  (*(volatile unsigned long *)(clkbase1 + 0xC228 ))
#define CLK_SRC_G3D                  (*(volatile unsigned long *)(clkbase1 + 0xC22C ))
#define CLK_SRC_LCD0                 (*(volatile unsigned long *)(clkbase1 + 0xC234 ))
#define CLK_SRC_ISP                  (*(volatile unsigned long *)(clkbase1 + 0xC238 ))
#define CLK_SRC_MAUDIO               (*(volatile unsigned long *)(clkbase1 + 0xC23C ))
#define CLK_SRC_FSYS                 (*(volatile unsigned long *)(clkbase1 + 0xC240 ))
#define CLK_SRC_PERIL0               (*(volatile unsigned long *)(clkbase1 + 0xC250 ))
#define CLK_SRC_PERIL1               (*(volatile unsigned long *)(clkbase1 + 0xC254 ))
#define CLK_SRC_CAM1                 (*(volatile unsigned long *)(clkbase1 + 0xC258 ))
#define CLK_SRC_MASK_CAM0            (*(volatile unsigned long *)(clkbase1 + 0xC320 ))
#define CLK_SRC_MASK_TV              (*(volatile unsigned long *)(clkbase1 + 0xC324 ))
#define CLK_SRC_MASK_LCD             (*(volatile unsigned long *)(clkbase1 + 0xC334 ))
#define CLK_SRC_MASK_ISP             (*(volatile unsigned long *)(clkbase1 + 0xC338 ))
#define CLK_SRC_MASK_MAUDIO          (*(volatile unsigned long *)(clkbase1 + 0xC33C ))
#define CLK_SRC_MASK_FSYS            (*(volatile unsigned long *)(clkbase1 + 0xC340 ))
#define CLK_SRC_MASK_PERIL0          (*(volatile unsigned long *)(clkbase1 + 0xC350 ))
#define CLK_SRC_MASK_PERIL1          (*(volatile unsigned long *)(clkbase1 + 0xC354 ))
#define CLK_MUX_STAT_TOP0            (*(volatile unsigned long *)(clkbase1 + 0xC410 ))
#define CLK_MUX_STAT_TOP1            (*(volatile unsigned long *)(clkbase1 + 0xC414 ))
#define CLK_MUX_STAT_MFC             (*(volatile unsigned long *)(clkbase1 + 0xC428 ))
#define CLK_MUX_STAT_G3D             (*(volatile unsigned long *)(clkbase1 + 0xC42C ))
#define CLK_MUX_STAT_CAM1            (*(volatile unsigned long *)(clkbase1 + 0xC458 ))
#define CLK_DIV_TOP                  (*(volatile unsigned long *)(clkbase1 + 0xC510 ))
#define CLK_DIV_CAM0                 (*(volatile unsigned long *)(clkbase1 + 0xC520 ))
#define CLK_DIV_TV                   (*(volatile unsigned long *)(clkbase1 + 0xC524 ))
#define CLK_DIV_MFC                  (*(volatile unsigned long *)(clkbase1 + 0xC528 ))
#define CLK_DIV_G3D                  (*(volatile unsigned long *)(clkbase1 + 0xC52C ))
#define CLK_DIV_LCD                  (*(volatile unsigned long *)(clkbase1 + 0xC534 ))
#define CLK_DIV_ISP                  (*(volatile unsigned long *)(clkbase1 + 0xC538 ))
#define CLK_DIV_MAUDIO               (*(volatile unsigned long *)(clkbase1 + 0xC53C ))
#define CLK_DIV_FSYS0                (*(volatile unsigned long *)(clkbase1 + 0xC540 ))
#define CLK_DIV_FSYS1                (*(volatile unsigned long *)(clkbase1 + 0xC544 ))
#define CLK_DIV_FSYS2                (*(volatile unsigned long *)(clkbase1 + 0xC548 ))
#define CLK_DIV_FSYS3                (*(volatile unsigned long *)(clkbase1 + 0xC54C ))
#define CLK_DIV_PERIL0               (*(volatile unsigned long *)(clkbase1 + 0xC550 ))
#define CLK_DIV_PERIL1               (*(volatile unsigned long *)(clkbase1 + 0xC554 ))
#define CLK_DIV_PERIL2               (*(volatile unsigned long *)(clkbase1 + 0xC558 ))
#define CLK_DIV_PERIL3               (*(volatile unsigned long *)(clkbase1 + 0xC55C ))
#define CLK_DIV_PERIL4               (*(volatile unsigned long *)(clkbase1 + 0xC560 ))
#define CLK_DIV_PERIL5               (*(volatile unsigned long *)(clkbase1 + 0xC564 ))
#define CLK_DIV_CAM1                 (*(volatile unsigned long *)(clkbase1 + 0xC568 ))
#define CLKDIV2_RATIO                (*(volatile unsigned long *)(clkbase1 + 0xC580 ))
#define CLK_DIV_STAT_TOP             (*(volatile unsigned long *)(clkbase1 + 0xC610 ))
#define CLK_DIV_STAT_CAM0            (*(volatile unsigned long *)(clkbase1 + 0xC620 ))
#define CLK_DIV_STAT_TV              (*(volatile unsigned long *)(clkbase1 + 0xC624 ))
#define CLK_DIV_STAT_MFC             (*(volatile unsigned long *)(clkbase1 + 0xC628 ))
#define CLK_DIV_STAT_G3D             (*(volatile unsigned long *)(clkbase1 + 0xC62C ))
#define CLK_DIV_STAT_LCD             (*(volatile unsigned long *)(clkbase1 + 0xC634 ))
#define CLK_DIV_STAT_ISP             (*(volatile unsigned long *)(clkbase1 + 0xC638 ))
#define CLK_DIV_STAT_MAUDIO          (*(volatile unsigned long *)(clkbase1 + 0xC63C ))
#define CLK_DIV_STAT_FSYS0           (*(volatile unsigned long *)(clkbase1 + 0xC640 ))
#define CLK_DIV_STAT_FSYS1           (*(volatile unsigned long *)(clkbase1 + 0xC644 ))
#define CLK_DIV_STAT_FSYS2           (*(volatile unsigned long *)(clkbase1 + 0xC648 ))
#define CLK_DIV_STAT_FSYS3           (*(volatile unsigned long *)(clkbase1 + 0xC64C ))
#define CLK_DIV_STAT_PERIL0          (*(volatile unsigned long *)(clkbase1 + 0xC650 ))
#define CLK_DIV_STAT_PERIL1          (*(volatile unsigned long *)(clkbase1 + 0xC654 ))
#define CLK_DIV_STAT_PERIL2          (*(volatile unsigned long *)(clkbase1 + 0xC658 ))
#define CLK_DIV_STAT_PERIL3          (*(volatile unsigned long *)(clkbase1 + 0xC65C ))
#define CLK_DIV_STAT_PERIL4          (*(volatile unsigned long *)(clkbase1 + 0xC660 ))
#define CLK_DIV_STAT_PERIL5          (*(volatile unsigned long *)(clkbase1 + 0xC664 ))
#define CLK_DIV_STAT_CAM1            (*(volatile unsigned long *)(clkbase1 + 0xC668 ))
#define CLKDIV2_STAT                 (*(volatile unsigned long *)(clkbase1 + 0xC680 ))
#define CLK_GATE_BUS_FSYS1           (*(volatile unsigned long *)(clkbase1 + 0xC744 ))
#define CLK_GATE_IP_CAM              (*(volatile unsigned long *)(clkbase1 + 0xC920 ))
#define CLK_GATE_IP_TV               (*(volatile unsigned long *)(clkbase1 + 0xC924 ))
#define CLK_GATE_IP_MFC              (*(volatile unsigned long *)(clkbase1 + 0xC928 ))
#define CLK_GATE_IP_G3D              (*(volatile unsigned long *)(clkbase1 + 0xC92C ))
#define CLK_GATE_IP_LCD              (*(volatile unsigned long *)(clkbase1 + 0xC934 ))
#define CLK_GATE_IP_ISP              (*(volatile unsigned long *)(clkbase1 + 0xC938 ))
#define CLK_GATE_IP_FSYS             (*(volatile unsigned long *)(clkbase1 + 0xC940 ))
#define CLK_GATE_IP_GPS              (*(volatile unsigned long *)(clkbase1 + 0xC94C ))
#define CLK_GATE_IP_PERIL            (*(volatile unsigned long *)(clkbase1 + 0xC950 ))
#define CLK_GATE_BLOCK               (*(volatile unsigned long *)(clkbase1 + 0xC970 ))
#define CLKOUT_CMU_TOP               (*(volatile unsigned long *)(clkbase1 + 0xCA00 ))
#define CLKOUT_CMU_TOP_DIV_STAT      (*(volatile unsigned long *)(clkbase1 + 0xCA04 ))

#define clkbase2 0x10040000
#define MPLL_LOCK                    (*(volatile unsigned long *)(clkbase2 + 0x0008))
#define MPLL_CON0                    (*(volatile unsigned long *)(clkbase2 + 0x0108 ))
#define MPLL_CON1                    (*(volatile unsigned long *)(clkbase2 + 0x010C ))
#define CLK_SRC_DMC                  (*(volatile unsigned long *)(clkbase2 + 0x0200))
#define CLK_SRC_MASK_DMC             (*(volatile unsigned long *)(clkbase2 + 0x0300))
#define CLK_MUX_STAT_DMC             (*(volatile unsigned long *)(clkbase2 + 0x0400 ))
#define CLK_DIV_DMC0                 (*(volatile unsigned long *)(clkbase2 + 0x0500 ))
#define CLK_DIV_DMC1                 (*(volatile unsigned long *)(clkbase2 + 0x0504 ))
#define CLK_DIV_STAT_DMC0            (*(volatile unsigned long *)(clkbase2 + 0x0600))
#define CLK_DIV_STAT_DMC1            (*(volatile unsigned long *)(clkbase2 + 0x0604))
#define CLK_GATE_BUS_DMC0            (*(volatile unsigned long *)(clkbase2 + 0x0700 ))
#define CLK_GATE_BUS_DMC1            (*(volatile unsigned long *)(clkbase2 + 0x0704 ))
#define CLK_GATE_IP_DMC0             (*(volatile unsigned long *)(clkbase2 + 0x0900))
#define CLK_GATE_IP_DMC1             (*(volatile unsigned long *)(clkbase2 + 0x0904))
#define CLKOUT_CMU_DMC               (*(volatile unsigned long *)(clkbase2 + 0x0A00))
#define CLKOUT_CMU_DMC_DIV_STAT      (*(volatile unsigned long *)(clkbase2 + 0x0A04))
#define DCGIDX_MAP0                  (*(volatile unsigned long *)(clkbase2 + 0x1000))
#define DCGIDX_MAP1                  (*(volatile unsigned long *)(clkbase2 + 0x1004))
#define DCGIDX_MAP2                  (*(volatile unsigned long *)(clkbase2 + 0x1008))
#define DCGPERF_MAP0                 (*(volatile unsigned long *)(clkbase2 + 0x1020 ))
#define DCGPERF_MAP1                 (*(volatile unsigned long *)(clkbase2 + 0x1024 ))
#define DVCIDX_MAP 		     (*(volatile unsigned long *)(clkbase2 + 0x1040))
#define FREQ_CPU                     (*(volatile unsigned long *)(clkbase2 + 0x1060))
#define FREQ_DPM                     (*(volatile unsigned long *)(clkbase2 + 0x1064))
#define DVSEMCLK_EN                  (*(volatile unsigned long *)(clkbase2 + 0x1080))
#define MAXPERF                      (*(volatile unsigned long *)(clkbase2 + 0x1084))
#define DMC_PAUSE_CTRL               (*(volatile unsigned long *)(clkbase2 + 0x1094))
#define DDRPHY_LOCK_CTRL             (*(volatile unsigned long *)(clkbase2 + 0x1098))
#define C2C_STATE                    (*(volatile unsigned long *)(clkbase2 + 0x109C ))
#define APLL_LOCK                    (*(volatile unsigned long *)(clkbase2 + 0x4000))
#define APLL_CON0                    (*(volatile unsigned long *)(clkbase2 + 0x4100))
#define APLL_CON1                    (*(volatile unsigned long *)(clkbase2 + 0x4104))
#define CLK_SRC_CPU                  (*(volatile unsigned long *)(clkbase2 + 0x4200))
#define CLK_MUX_STAT_CPU             (*(volatile unsigned long *)(clkbase2 + 0x4400))
#define CLK_DIV_CPU0                 (*(volatile unsigned long *)(clkbase2 + 0x4500))
#define CLK_DIV_CPU1                 (*(volatile unsigned long *)(clkbase2 + 0x4504))
#define CLK_DIV_STAT_CPU0            (*(volatile unsigned long *)(clkbase2 + 0x4600))
#define CLK_DIV_STAT_CPU1            (*(volatile unsigned long *)(clkbase2 + 0x4604))
#define CLK_GATE_IP_CPU              (*(volatile unsigned long *)(clkbase2 + 0x4900))
#define CLKOUT_CMU_CPU               (*(volatile unsigned long *)(clkbase2 + 0x4A00))
#define CLKOUT_CMU_CPU_DIV_STAT      (*(volatile unsigned long *)(clkbase2 + 0x4A04))
#define ARMCLK_STOPCTRL              (*(volatile unsigned long *)(clkbase2 + 0x5000 ))
#define ATCLK_STOPCTRL               (*(volatile unsigned long *)(clkbase2 + 0x5004 ))
#define PWR_CTRL                     (*(volatile unsigned long *)(clkbase2 + 0x5020 ))
#define PWR_CTRL2                    (*(volatile unsigned long *)(clkbase2 + 0x5024 ))
#define L2_STATUS                    (*(volatile unsigned long *)(clkbase2 + 0x5400))
#define CPU_STATUS                   (*(volatile unsigned long *)(clkbase2 + 0x5410))
#define PTM_STATUS                   (*(volatile unsigned long *)(clkbase2 + 0x5420 ))
#define CLK_DIV_ISP0                 (*(volatile unsigned long *)(clkbase2 + 0x8300 ))
#define CLK_DIV_ISP1                 (*(volatile unsigned long *)(clkbase2 + 0x8304 ))
#define CLK_DIV_STAT_ISP0            (*(volatile unsigned long *)(clkbase2 + 0x8400 ))
#define CLK_DIV_STAT_ISP1            (*(volatile unsigned long *)(clkbase2 + 0x8404 ))
#define CLK_GATE_IP_ISP0             (*(volatile unsigned long *)(clkbase2 + 0x8800))
#define CLK_GATE_IP_ISP1             (*(volatile unsigned long *)(clkbase2 + 0x8804))
#define CLKOUT_CMU_ISP               (*(volatile unsigned long *)(clkbase2 + 0x8A00 ))
#define CLKOUT_CMU_ISP_DIV_STAT      (*(volatile unsigned long *)(clkbase2 + 0x8A04 ))
#define CMU_ISP_SPARE0               (*(volatile unsigned long *)(clkbase2 + 0x8B00 ))
#define CMU_ISP_SPARE1               (*(volatile unsigned long *)(clkbase2 + 0x8B04 ))
#define CMU_ISP_SPARE2               (*(volatile unsigned long *)(clkbase2 + 0x8B08 ))
#define CMU_ISP_SPARE3               (*(volatile unsigned long *)(clkbase2 + 0x8B0C ))

#define lcdbase 0x11c00000
#define VIDCON0      (*(volatile unsigned long *)(lcdbase + 0x0000)) 
#define VIDCON1      (*(volatile unsigned long *)(lcdbase + 0x0004)) 
#define VIDCON2      (*(volatile unsigned long *)(lcdbase + 0x0008)) 
#define VIDCON3      (*(volatile unsigned long *)(lcdbase + 0x000C)) 
#define VIDTCON0     (*(volatile unsigned long *)(lcdbase + 0x0010)) 
#define VIDTCON1     (*(volatile unsigned long *)(lcdbase + 0x0014)) 
#define VIDTCON2     (*(volatile unsigned long *)(lcdbase + 0x0018)) 
#define VIDTCON3     (*(volatile unsigned long *)(lcdbase + 0x001C)) 
#define WINCON0      (*(volatile unsigned long *)(lcdbase + 0x0020)) 
#define WINCON1      (*(volatile unsigned long *)(lcdbase + 0x0024)) 
#define WINCON2      (*(volatile unsigned long *)(lcdbase + 0x0028)) 
#define WINCON3      (*(volatile unsigned long *)(lcdbase + 0x002C)) 
#define WINCON4      (*(volatile unsigned long *)(lcdbase + 0x0030)) 
#define SHADOWCON    (*(volatile unsigned long *)(lcdbase + 0x0034)) 
#define WINCHMAP2    (*(volatile unsigned long *)(lcdbase + 0x003C)) 
#define VIDOSD0A     (*(volatile unsigned long *)(lcdbase + 0x0040)) 
#define VIDOSD0B     (*(volatile unsigned long *)(lcdbase + 0x0044)) 
#define VIDOSD0C     (*(volatile unsigned long *)(lcdbase + 0x0048)) 
#define VIDOSD1A     (*(volatile unsigned long *)(lcdbase + 0x0050)) 
#define VIDOSD1B     (*(volatile unsigned long *)(lcdbase + 0x0054)) 
#define VIDOSD1C     (*(volatile unsigned long *)(lcdbase + 0x0058)) 
#define VIDOSD1D     (*(volatile unsigned long *)(lcdbase + 0x005C)) 
#define VIDOSD2A     (*(volatile unsigned long *)(lcdbase + 0x0060)) 
#define VIDOSD2B     (*(volatile unsigned long *)(lcdbase + 0x0064)) 
#define VIDOSD2C     (*(volatile unsigned long *)(lcdbase + 0x0068)) 
#define VIDOSD2D     (*(volatile unsigned long *)(lcdbase + 0x006C)) 
#define VIDOSD3A     (*(volatile unsigned long *)(lcdbase + 0x0070)) 
#define VIDOSD3B     (*(volatile unsigned long *)(lcdbase + 0x0074)) 
#define VIDOSD3C     (*(volatile unsigned long *)(lcdbase + 0x0078)) 
#define VIDOSD4A     (*(volatile unsigned long *)(lcdbase + 0x0080)) 
#define VIDOSD4B     (*(volatile unsigned long *)(lcdbase + 0x0084)) 
#define VIDOSD4C     (*(volatile unsigned long *)(lcdbase + 0x0088)) 
#define VIDW00ADD0B0 (*(volatile unsigned long *)(lcdbase + 0x00A0)) 
#define VIDW00ADD0B1 (*(volatile unsigned long *)(lcdbase + 0x00A4)) 
#define VIDW00ADD0B2 (*(volatile unsigned long *)(lcdbase + 0x20A0)) 
#define VIDW01ADD0B0 (*(volatile unsigned long *)(lcdbase + 0x00A8)) 
#define VIDW01ADD0B1 (*(volatile unsigned long *)(lcdbase + 0x00AC)) 
#define VIDW01ADD0B2 (*(volatile unsigned long *)(lcdbase + 0x20A8)) 
#define VIDW02ADD0B0 (*(volatile unsigned long *)(lcdbase + 0x00B0)) 
#define VIDW02ADD0B1 (*(volatile unsigned long *)(lcdbase + 0x00B4)) 
#define VIDW02ADD0B2 (*(volatile unsigned long *)(lcdbase + 0x20B0)) 
#define VIDW03ADD0B0 (*(volatile unsigned long *)(lcdbase + 0x00B8)) 
#define VIDW03ADD0B1 (*(volatile unsigned long *)(lcdbase + 0x00BC)) 
#define VIDW03ADD0B2 (*(volatile unsigned long *)(lcdbase + 0x20B8)) 
#define VIDW04ADD0B0 (*(volatile unsigned long *)(lcdbase + 0x00C0)) 
#define VIDW04ADD0B1 (*(volatile unsigned long *)(lcdbase + 0x00C4)) 
#define VIDW04ADD0B2 (*(volatile unsigned long *)(lcdbase + 0x20C0)) 
#define VIDW00ADD1B0 (*(volatile unsigned long *)(lcdbase + 0x00D0)) 
#define VIDW00ADD1B1 (*(volatile unsigned long *)(lcdbase + 0x00D4)) 
#define VIDW00ADD1B2 (*(volatile unsigned long *)(lcdbase + 0x20D0)) 
#define VIDW01ADD1B0 (*(volatile unsigned long *)(lcdbase + 0x00D8)) 
#define VIDW01ADD1B1 (*(volatile unsigned long *)(lcdbase + 0x00DC)) 
#define VIDW01ADD1B2 (*(volatile unsigned long *)(lcdbase + 0x20D8)) 
#define VIDW02ADD1B0 (*(volatile unsigned long *)(lcdbase + 0x00E0)) 
#define VIDW02ADD1B1 (*(volatile unsigned long *)(lcdbase + 0x00E4)) 
#define VIDW02ADD1B2 (*(volatile unsigned long *)(lcdbase + 0x20E0)) 
#define VIDW03ADD1B0 (*(volatile unsigned long *)(lcdbase + 0x00E8)) 
#define VIDW03ADD1B1 (*(volatile unsigned long *)(lcdbase + 0x00EC)) 
#define VIDW03ADD1B2 (*(volatile unsigned long *)(lcdbase + 0x20E8)) 
#define VIDW04ADD1B0 (*(volatile unsigned long *)(lcdbase + 0x00F0)) 
#define VIDW04ADD1B1 (*(volatile unsigned long *)(lcdbase + 0x00F4)) 
#define VIDW04ADD1B2 (*(volatile unsigned long *)(lcdbase + 0x20F0)) 
#define VIDW00ADD2   (*(volatile unsigned long *)(lcdbase + 0x0100)) 
#define VIDW01ADD2   (*(volatile unsigned long *)(lcdbase + 0x0104)) 
#define VIDW02ADD2   (*(volatile unsigned long *)(lcdbase + 0x0108)) 
#define VIDW03ADD2   (*(volatile unsigned long *)(lcdbase + 0x010C)) 
#define VIDW04ADD2   (*(volatile unsigned long *)(lcdbase + 0x0110)) 
#define VIDINTCON0   (*(volatile unsigned long *)(lcdbase + 0x0130)) 

#define  sysrbase 	0x10010000
#define GENERAL_CTRL_C2C (*(volatile unsigned long *)(sysrbase + 0x010C)) 
#define GENERAL_CTRL_GPS (*(volatile unsigned long *)(sysrbase + 0x0110)) 
#define ADC_CFG 	 (*(volatile unsigned long *)(sysrbase + 0x0118)) 
#define ISPBLK_CFG       (*(volatile unsigned long *)(sysrbase + 0x020C)) 
#define LCDBLK_CFG       (*(volatile unsigned long *)(sysrbase + 0x0210)) 
#define LCDBLK_CFG2      (*(volatile unsigned long *)(sysrbase + 0x0214)) 
#define CAMBLK_CFG       (*(volatile unsigned long *)(sysrbase + 0x0218)) 
#define USB_CFG          (*(volatile unsigned long *)(sysrbase + 0x021C)) 
#define PPMU_CON         (*(volatile unsigned long *)(sysrbase + 0x0320)) 
#define SMMU_CON         (*(volatile unsigned long *)(sysrbase + 0x0330)) 

